# Generated by Django 5.1.1 on 2024-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('results', models.JSONField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
